M48
; DRILL file {KiCad 8.0.7} date 2024-12-27T12:04:43+1100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-27T12:04:43+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0650
%
G90
G05
T1
X6.7943Y-4.0039
T2
X4.6211Y-3.3441
T3
X7.6211Y-4.0039
M30
